apiVersion: 1

datasources:
  - name: csv-datasource
    uid: 1257c93b-f998-438c-a784-7e90fb94fb36
    type: marcusolsson-csv-datasource
    url: /workspace/dfp_detections_azure.csv
    access: "proxy"
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      storage: local