# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

vdb_pipeline:
  sources:
    - type: rss
      name: "rss_cve"
      config:
        feed_input:
          - "https://www.theregister.com/security/headlines.atom"
          - "https://isc.sans.edu/dailypodcast.xml"
          - "https://threatpost.com/feed/"
          - "http://feeds.feedburner.com/TheHackersNews?format=xml"
          - "https://www.bleepingcomputer.com/feed/"
          - "https://therecord.media/feed/"
          - "https://blog.badsectorlabs.com/feeds/all.atom.xml"
          - "https://krebsonsecurity.com/feed/"
          - "https://www.darkreading.com/rss_simple.asp"
          - "https://blog.malwarebytes.com/feed/"
          - "https://msrc.microsoft.com/blog/feed"
          - "https://securelist.com/feed"
          - "https://www.crowdstrike.com/blog/feed/"
          - "https://threatconnect.com/blog/rss/"
          - "https://news.sophos.com/en-us/feed/"
          - "https://www.us-cert.gov/ncas/current-activity.xml"
          - "https://www.csoonline.com/feed"
          - "https://www.cyberscoop.com/feed"
          - "https://research.checkpoint.com/feed"
          - "https://feeds.fortinet.com/fortinet/blog/threat-research"
          - "https://www.mcafee.com/blogs/rss"
          - "https://www.digitalshadows.com/blog-and-research/rss.xml"
          - "https://www.nist.gov/news-events/cybersecurity/rss.xml"
          - "https://www.sentinelone.com/blog/rss/"
          - "https://www.bitdefender.com/blog/api/rss/labs/"
          - "https://www.welivesecurity.com/feed/"
          - "https://unit42.paloaltonetworks.com/feed/"
          - "https://mandiant.com/resources/blog/rss.xml"
          - "https://www.wired.com/feed/category/security/latest/rss"
          - "https://www.wired.com/feed/tag/ai/latest/rss"
          - "https://blog.google/threat-analysis-group/rss/"
          - "https://intezer.com/feed/"
        batch_size: 1024
        cache_dir: "./.cache/http"
        cooldown_interval: 600
        enable_cache: False
        enable_monitor: True
        interval_secs: 600
        request_timeout: 2.0
        run_indefinitely: true
        stop_after: 0
        web_scraper_config:
          chunk_size: 512
          enable_cache: false

    - type: filesystem
      name: "demo_filesystem_source"
      config:
        batch_size: 1024
        enable_monitor: False
        extractor_config:
          chunk_size: 512
          num_threads: 10 # Number of threads to use for file reads
        filenames:
          - "morpheus/data/scratch/random_cybersecurity_data.txt"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-1.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-2.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-3.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-4.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-5.pdf"
          - "models/datasets/training-data/log-parsing-training-data.csv"
        watch: false
        converters_meta:
            csv:
              text_column_name: "raw" # Requires same schema for all CSV files.

    # Custom source example -- Here we just use the filesystem source but specify the module to use, explicitly.
    - type: custom
      name: "demo_custom_source"
      config:
        config_name_mapping: "file_source_config"
        namespace: "morpheus_examples_llm"
        module_id: "file_source_pipe"
        module_output_id: "output"
        batch_size: 1024
        filenames:
          - "morpheus/data/scratch/random_cybersecurity_data.txt"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-1.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-2.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-3.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-4.pdf"
          - "morpheus/data/scratch/the-un-security-council-handbook-by-scr-5.pdf"
        watch: false

  embeddings:
    model_name: "all-MiniLM-L6-v2"
    model_kwargs:
      - device: "cuda"
    encode_kwargs:
      - normalize_embeddings: true
    size: 384

  vdb:
    service: "milvus"  # Specify the type of vector database
    uri: "http://localhost:19530"  # URI for connecting to the Vector Database server
    resource_name: "VDB2"  # Identifier for the resource in the vector database
    recreate: True  # Whether to recreate the resource if it already exists
