# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: '3.3'

name: cyber-dev-day

services:

  # Run `docker compose build morpheus` to help build the base Morpheus container
  morpheus:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        - MORPHEUS_ROOT_HOST=.
      target: development
    image: nvcr.io/nvidia/morpheus/morpheus:v24.03.00-cyber-dev-day
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - ../..:/workspace
    profiles:
      # This disables this service when running `docker compose up`
      - build

  cyber-dev-day:
    build:
      context: ../..
      dockerfile: ./examples/cyber_dev_day/Dockerfile
      args:
        - MORPHEUS_CONTAINER=${MORPHEUS_CONTAINER:-nvcr.io/nvidia/morpheus/morpheus}
        - MORPHEUS_CONTAINER_VERSION=${MORPHEUS_CONTAINER_VERSION:-v24.03.00-cyber-dev-day}
      target: jupyter
    image: morpheus-cyber-dev-day
    ports:
      - "26302"
      - "8888:8888"
    working_dir: /workspace/examples/cyber_dev_day
    command: jupyter-lab --no-browser --allow-root --ip='*'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    networks:
      - proxy
    # Uncomment if the .env file issue is resolved: https://github.com/docker/compose/issues/9181#issuecomment-1996016211
    # env_file:
    #   - path: .env
    #     required: "false"
    environment:
      - TERM=${TERM:-}
      # Workaround until this is working: https://github.com/docker/compose/issues/9181#issuecomment-1996016211
      - NGC_API_KEY=${NGC_API_KEY:-CYBER_DEV_DAY}
      - NGC_ORG_ID=${NGC_ORG_ID:-CYBER_DEV_DAY}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY:-nvapi-CYBER_DEV_DAY}
      # Overwrite any environment variables in the .env file with URLs needed in the network
      - NGC_API_BASE=http://morpheuscache.ddns.net/nemo/v1
      - NVIDIA_API_BASE=http://morpheuscache.ddns.net/nvcf/v2
      - OPENAI_API_BASE=http://morpheuscache.ddns.net/openai/v1
      - OPENAI_BASE_URL=http://morpheuscache.ddns.net/openai/v1
    volumes:
      - ../..:/workspace
      - build-cache:/workspace/.cache
      - build-dir:/workspace/build-docker
    cap_add:
      - sys_nice
    depends_on:
      - proxy-cache
    restart: always

  proxy-cache:
    image: nginx:1.23.4
    ports:
      - "81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/template-variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
      - proxy-cache:/server_cache:rw
    env_file:
      - path: .env
        required: false
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

volumes:
  proxy-cache:
    driver: local
  build-cache:
    driver: local
  build-dir:
    driver: local
