name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Morpheus are you running?
      placeholder: "example: 22.09"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Which installation methods does this occur on?
      multiple: true
      options:
        - Docker
        - Conda
        - Source

  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe the bug.
      description: Also tell us, what did you expect to happen?
      placeholder: XYZ occured, I expected QRS results
    validations:
      required: true

  - type: textarea
    id: mvr
    attributes:
      label: Minimum reproducible example
      description: Please supply a [minimum reproducible code example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) here
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste relevant error and log output here
      render: shell

  - type: textarea
    id: env-printout
    attributes:
      label: Full env printout
      description: Please run and paste the output of the `./scripts/print_env.sh` script here, to gather any other relevant environment details
      render: shell

  - type: textarea
    id: misc
    attributes:
      label: Other/Misc.
      description: Please enter any other helpful information here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nv-morpheus/Morpheus/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Morpheus' Code of Conduct
          required: true
