# SPDX-FileCopyrightText: Copyright (c) 2021-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: morpheus
channels:
  - conda-forge
  - numba
  - nvidia
  - nvidia/label/cuda-11.8.0
  - nvidia/label/dev # For pre-releases of MRC. Should still default to full releases if available
  - rapidsai
dependencies:
  ####### Morpheus Dependencies (keep sorted!) #######
  - automake=1.16.5
  - benchmark=1.6.1
  - boost-cpp=1.74
  - cachetools=5.0.0
  - ccache>=3.7
  - clangdev=14
  - click >=8
  - cmake=3.24
  - configargparse=1.5
  - cuda-compiler=11.8
  - cuda-nvml-dev=11.8
  - cudatoolkit=11.8
  - cudf 23.02
  - cupy=9.5.0
  - cxx-compiler
  - cython=0.29.24
  - datacompy=0.8
  - dill
  - docker-compose=1.29.2
  - docker-py=5.0
  - faker=12.3.0
  - flake8
  - flatbuffers=2.0
  - gcc_linux-64=11.2
  - gflags=2.2
  - git-lfs=3.2
  - git>=2.35.3 # Needed for wildcards on safe.directory
  - glog=0.6
  - gmock=1.10
  - gputil
  - grpc-cpp>=1.43
  - grpcio
  - gtest=1.10
  - gxx_linux-64=11.2
  - include-what-you-use=0.18
  - isort
  - librdkafka=1.7.0
  - merlin-core>=23.02.01  #  Necessary until https://github.com/NVIDIA-Merlin/NVTabular/issues/1793 is resolved
  - merlin-dataloader=23.02.01  #  Necessary until https://github.com/NVIDIA-Merlin/NVTabular/issues/1793 is resolved
  - mlflow>1.29,<2
  - mrc=23.07
  - myst-parser==0.17
  - networkx=2.8
  - ninja=1.10
  - nodejs=17.4.0
  - numba>=0.56.2
  - numpydoc=1.4
  - nvtabular>=23.02
  - pandas=1.3
  - pip
  - pkg-config # for mrc cmake
  - pluggy=1.0
  - protobuf=4.21.*
  - pybind11-stubgen=0.10.5
  - pydot
  - pytest
  - pytest-benchmark>=4.0
  - pytest-cov
  - python-confluent-kafka=1.7.0
  - python-graphviz
  - python=3.8
  - rapidjson=1.1.0
  - scikit-build=0.13
  - scikit-learn=0.23.1
  - sphinx
  - sphinx_rtd_theme
  - sysroot_linux-64=2.17
  - tritonclient>=2.26 #  Required by NvTabular, force the version, so we get protobuf compatible with 4.21
  - tqdm=4
  - typing_utils=0.1
  - watchdog=2.1
  - yapf=0.32.0
  ####### Morpheus Pip Dependencies (keep sorted!) #######
  - pip:
      # Add additional dev dependencies here
      - docutils
      # Ensure all runtime requirements are installed using the requirements file
      - --requirement requirements.txt
