 name: Automatic requirements.txt for Python Projects
 on:
  push:
    branches: [ branch-22.06 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ branch-22.06 ]
  schedule:
    - cron: '35 6 * * 5'
    
 jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
          
    steps:
    - uses: ryan-rozario/pipreqs-action@v2.0.0
      with:
    # Gives the path of the project 
       PROJECT_PATH: morpheus/docs
       REQUIREMENT_PATH: morpheus/docs/requirement.txt
       PROJECT_NAME: morpheus
    
      # uses: ryan-rozario/pipreqs-action@071f0f2af11e5e65226d8b7353bf76465adb86a2
            #        name: Conda
      # uses: docker/conda/environments/requirements.txt
      #        name: GNN Fraud Detection Pipeline
      # uses: examples/gnn_fraud_detection_pipeline/requirements.yml
      #        name: ABP Models
      # uses: models/validation-inference-scripts/abp-models/requirements.txt
      #        name: Hammah Models
      # uses:  models/validation-inference-scripts/hammah-models/requirements.txt
      #        name: Phishing Models, Validation
      # uses: models/validation-inference-scripts/phishing-models/requirements.txt
      #        name: Fraud Detection, Training
      # uses: models/training-tuning-scripts/fraud-detection-models/requirements.txt
      #        name: Fraud Detection, Validation
      # uses: models/validation-inference-scripts/fraud-detection-models/requirements.txt
