# SPDX-FileCopyrightText: Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Pipeline

on:
  workflow_call:
    inputs:
      run_check:
        required: true
        type: boolean
      container:
        required: true
        type: string
      test_container:
        required: true
        type: string
    secrets:
      NGC_API_KEY:
        required: true

env:
  CHANGE_TARGET: "${{ github.base_ref }}"
  CUDA_PATH: "/usr/local/cuda/"
  CUDA_VER: "11.8"
  GH_TOKEN: "${{ github.token }}"
  GIT_COMMIT: "${{ github.sha }}"
  MORPHEUS_ROOT: "${{ github.workspace }}/morpheus"
  WORKSPACE: "${{ github.workspace }}/morpheus"
  WORKSPACE_TMP: "${{ github.workspace }}/tmp"

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  check:
    if: ${{ inputs.run_check }}
    name: Check
    runs-on: linux-amd64-cpu4
    timeout-minutes: 60
    container:
      credentials:
        username: '$oauthtoken'
        password: ${{ secrets.NGC_API_KEY }}
      image: ${{ inputs.container }}
    strategy:
      fail-fast: true
